base_url = "https://vincenzocalabretta.dev"
title = "A bunch of notes"
description = "A repository of development notes for future self or for you."
default_language = "en"
compile_sass = false
minify_html = false
generate_feeds = false
